# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This script generates jit/GuardDescriptorArgKinds.h from CacheIROps.yaml

import io

import buildconfig
import yaml
from mozbuild.preprocessor import Preprocessor

HEADER_TEMPLATE = """\
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef %(includeguard)s
#define %(includeguard)s

/* This file is generated by jit/GenerateGuardDescriptorArgKinds.py. Do not edit! */

%(contents)s

#endif // %(includeguard)s
"""


def load_yaml(yaml_path):
    # First invoke preprocessor.py so that we can use #ifdef JS_SIMULATOR in
    # the YAML file.
    pp = Preprocessor()
    pp.context.update(buildconfig.defines["ALLDEFINES"])
    pp.out = io.StringIO()
    pp.do_filter("substitution")
    pp.do_include(yaml_path)
    contents = pp.out.getvalue()
    return yaml.safe_load(contents)


def generate_guard_descriptor_arg_kinds_header(c_out, yaml_path):
    """Generate GuardDescriptorArgKindsGenerated.h from CacheIROps.yaml."""

    data = load_yaml(yaml_path)

    contents = """
#define GUARD_DESCRIPTOR_TEST "Hello, world!"
    """  # TODO

    c_out.write(
        HEADER_TEMPLATE
        % {
            "includeguard": "jit_GuardDescriptorArgKindsGenerated_h",
            "contents": contents,
        }
    )
